// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1730778574);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1730777974);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1730778334);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1730778214);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1730778094);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1730778454);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1730778004);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1730778694);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 20511);
user_pref("browser.cache.disk.capacity", 890880);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1730777944);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a9af20b2-c695-4027-bacd-da6f7d5bad6b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1730777969050");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1730779787050");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1730777949363");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1730799549363");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1730777948");
user_pref("browser.slowStartup.averageTime", 2291);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_19\",\"url\":\"https://www.mozilla.org/firefox/welcome/19/\",\"expire\":1733702400000}");
user_pref("browser.startup.lastColdStartupCheck", 1730777945);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1730777948131");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "72072d66212b46a18b91f6ec6004efc0");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1730778574);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"bef67eb9-39da-4b05-a31e-cb1f4334fdc8\",\"formautofill@mozilla.org\":\"18de2ba7-ecdc-4f63-8906-6af897755718\",\"screenshots@mozilla.org\":\"cc81f901-f570-4957-911b-ad00e30d7d42\",\"webcompat-reporter@mozilla.org\":\"40a18939-92c3-482a-8178-22503cb0d8cd\",\"webcompat@mozilla.org\":\"227468c6-18ac-4096-af55-cc2edaaab412\",\"default-theme@mozilla.org\":\"2e2970ce-b42e-4065-b791-adc157424056\",\"google@search.mozilla.org\":\"d06dbf50-b8cf-47c8-b3e1-23ed6c9b6430\",\"amazondotcom@search.mozilla.org\":\"43559dad-d413-402f-87e1-f5d0b2fbf221\",\"bing@search.mozilla.org\":\"fa3ea33f-dbad-4dcf-be25-3f4fc401d07e\",\"ddg@search.mozilla.org\":\"fb67c515-43d8-4666-b3ba-f9cc2ab7d167\",\"ebay@search.mozilla.org\":\"47aa6bfb-07b8-4e33-846a-2528e4756b6c\",\"twitter@search.mozilla.org\":\"651c3e8f-fec4-493f-a1dd-a52b4bf8f735\",\"wikipedia@search.mozilla.org\":\"c6406d64-658f-4332-890e-9fc1a048e6ea\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1730778010);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20200602222727");
user_pref("media.gmp-manager.lastCheck", 1730778009);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1730778004);
user_pref("security.remote_settings.intermediates.checked", 1730778004);
user_pref("security.sandbox.content.tempDirSuffix", "1aa6eae9-de76-470f-a7d9-27bb12d219de");
user_pref("security.sandbox.plugin.tempDirSuffix", "d112abae-7f6d-439f-bdf6-75cf83490f54");
user_pref("services.blocklist.addons.checked", 1730778004);
user_pref("services.blocklist.gfx.checked", 1730778004);
user_pref("services.blocklist.plugins.checked", 1730778004);
user_pref("services.settings.clock_skew_seconds", 5);
user_pref("services.settings.last_etag", "\"1730775431187\"");
user_pref("services.settings.last_update_seconds", 1730778449);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1730778004);
user_pref("services.settings.main.cfr.last_check", 1730778004);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1730778004);
user_pref("services.settings.main.hijack-blocklists.last_check", 1730778004);
user_pref("services.settings.main.language-dictionaries.last_check", 1730778004);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1730778004);
user_pref("services.settings.main.public-suffix-list.last_check", 1730778004);
user_pref("services.settings.main.search-config.last_check", 1730778004);
user_pref("services.settings.main.sites-classification.last_check", 1730778004);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1730778004);
user_pref("services.settings.main.whats-new-panel.last_check", 1730778004);
user_pref("services.settings.security.onecrl.checked", 1730778004);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1730777943);
user_pref("toolkit.telemetry.cachedClientID", "3d1a9b42-dc01-4833-bb6f-e81ef2d2e1ad");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
